import { Dimensions, StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: "center",
        justifyContent: "flex-start",
    },
    scrollView: {
        width: "100%",
    },
    bannerContainer: {
        width: "100%",
        height: 200,
        overflow: "hidden",
    },
    bannerImage: {
        width: "100%",
        height: "100%",
        position: "absolute",
        top: 0,
        left: 0,
    },
    overlayContainer: {
        position: "absolute",
        // bottom: 20,
        // left: 20,
        backgroundColor: "rgba(0,0,0)",
        // padding: 10,
        width: "100%",
        height: "100%",
        // borderRadius: 5,
    },
    overlayUp: {
        flex: 1,
        justifyContent: "flex-end",
        alignItems: "flex-start",
        padding: 10,
        backgroundColor: "rgba(0,0,0)",
        flexDirection: "row",
    },
    overlayDown: {
        flex: 1,
        justifyContent: "flex-end",
        alignItems: "flex-end",
        backgroundColor: "rgba(0,0,0,0.0)",
        flexDirection: "row",
    },
    overlayDownLeft: {
        flex: 1,
        // justifyContent: "flex-end",
        alignContent: "flex-end",
        // alignItems: "flex-start",
        backgroundColor: "rgba(200,0,0,0.0)",
        flexDirection: "row",
        flexWrap: "wrap-reverse",
        gap: 5,
        padding: 5,
    },
    overlayDownRight: {
        flex: 1,
        justifyContent: "flex-end",
        alignItems: "flex-end",
        backgroundColor: "rgba(0,0,200,0.0)",
        flexDirection: "row",
        flexWrap: "wrap-reverse",
    },
    streamingIcon: {
        height: 45,
        aspectRatio: 1,
        resizeMode: "contain",
        // alignSelf: "center",
        backgroundColor: "rgba(0,0,0,0.1)",
        borderRadius: 90,
        margin: 5,
        padding: 1,
    },
    contentContainer: {
        padding: 20,
    },
    title: {
        fontSize: 24,
        fontWeight: "bold",
        // marginBottom: 10,
    },
    years: {
        fontSize: 18,
        marginBottom: 10,
        color: "lightgray",
        fontStyle: "italic",
        width: "100%",
        textAlign: "left",
        opacity: 0.7,
    },
    subTitle: {
        fontSize: 20,
        fontWeight: "bold",
        marginBottom: 10,
    },
    description: {
        fontSize: 16,
        marginBottom: 20,
        color: "lightgray",
        textAlign: "left",
    },
    seasonButton: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingVertical: 10,
        marginBottom: 5,
        backgroundColor: "#1b1e2b",
        borderRadius: 4,
    },
    seasonTitle: {
        fontSize: 18,
        fontWeight: "bold",
        marginLeft: 15,
    },
    seasonContent: {
        paddingVertical: 10,
        marginLeft: 15,
        marginBottom: 15,
    },
    participantsContainer: {
        flexDirection: "row",
        // display: 'contents',
        flexWrap: "wrap",
        width: "100%",
        // height: 100,
        // backgroundColor: "red",
        justifyContent: "flex-start",
        gap: 10
    },
    personContainer: {
        // backgroundColor: "blue",
        // margin: 5,
        alignItems: "center",
        justifyContent: "flex-start", // Changed from "center" to "flex-start"
        // flexDirection: "row",
        // backgroundColor: "red",
        // width: '33.33%',
        flex: 1,
        width: Dimensions.get('window').width / 3 - 30,
        // backgroundColor: 'green'
        // borderWidth: 1,
        // borderColor: 'gray',
        borderRadius: 5,
        marginVertical: 5,
        padding: 3,
        backgroundColor: '#212432',
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.20,
        shadowRadius: 1.41,

        elevation: 2,
    },
    personInfoText: {
        textAlign: "center",
        marginTop: 4,
        wordWrap: "normal",
        width: '100%',
    },
    personImageContainer: {
        width: 80,
        height: 80,
        borderRadius: 90,
        backgroundColor: "gray",
        marginTop: 5,
    },
});

export default styles;